name: Test Dependabot Updates

on:
  pull_request:
    branches: [ main ]
    paths:
      - 'requirements.txt'

jobs:
  test-updates:
    runs-on: windows-latest
    
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
          
      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          
      - name: Check Import Functionality
        run: |
          python -c "import watchdog, tkcalendar, packaging, requests; print('All imports successful')"
          
      # Zusätzliche Tests könnten hier hinzugefügt werden